#baseUrl = "http://tufokan.com"
languageCode = "hu-hu"

title = "Tű Fokán Művészeti Fesztivál 2018. június 27.-július 1., Garáb"
theme = "hugo-bootswatch"

[params]
[[menu.main]]
name = "Rólunk"
url = "/"
identifier = "about"
weight = 10
