languageCode = "hu-hu"
theme = "hugo-bootswatch"
title = "Tű Fokán Művészeti Fesztivál 2018. június 27.-július 1., Garáb"
[[menu.main]]
identifier = "about"
name = "Rólunk"
url = "/"
weight = 1
[params]
