---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  page:
    default_front_matter_template: page
  artist:
    default_front_matter_template: artist
upload_dir: static/images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
