---
upload_path: "/static/uploads"
frontmatter_file_url_template: "/static/uploads"
body_file_url_template: "/static/uploads"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  page:
    default_front_matter_template: page
  artist:
    default_front_matter_template: artist
version: 0.38.1
